[pytest]
addopts = --basetemp=.pytest_tmp
filterwarnings =
    ignore:The `update_forward_refs` method is deprecated; use `model_rebuild` instead\.:pydantic.warnings.PydanticDeprecatedSince20:gotrue\.types
